= LiquiDoc CMF Proof of Concept

This project is for demonstrating the potential power and complexity of a docs-as-code infrastructure.
Unlike a content management _system_ (CMS), LiquiDoc CMF will be an open _framework_ for developing documentation architecture.
It will hopefully be flexible enough to accommodate a huge range of docs challenges faced by complex software products, all without constraining implementers and users into proprietary or overly packaged alternatives.

The truth is, existing docs-as-code solutions like link:https://readthedocs.org/[ReadTheDocs], link:http://www.mkdocs.org/[MkDocs], or maybe even any simple static site generator solve probably 90% of software documentation needs that can currently be addressed in a docs-as-code environment.
For the more complex edge cases, with messy repos or highly conditional, interrelated products/editions, a truly open-ended solution still evades us.

== The Challenge

Our intention is to prove out a docs-as-code approach for solving highly complex documentation problems.
The complicating factors so far include:

multiple user roles::
For now, we have basic users, premium users, and developer users.
These are distinct audiences that engage with different editions of the product in different ways.

multiple overlapping products::
Our fictional product has a basic edition, an edition with “premium” features, and an overarching API for developers.
Yet core/basic product features and canonical information persist across all three of these interface offerings.

tracking across release versions::
Docs must closely match product releases.

multiple output formats::
So far, we need three distinct (but heavily overlapping) web “portal” interfaces, as well as 3 PDF editions (we still run old school).

== Usage

This repository is yours to clone or fork -- hack away!
Hopefully it will at least demonstrate some techniques that will help you get unstuck on any single-sourcing/docs-as-code obstacles you may be facing.

=== Requirements

Like any good implementation of a framework, this project is just a bunch of flat files.
These files establish configuration, data, and content for dummy documentation of a nonexistent product.
All you need is the *Ruby runtime environment* and *Bundler*, as instructed in the link:https://github.com/briandominick/liquidoc-gem#installation[LiquiDoc README].

[NOTE]
This repo is *not a framework* in and of itself.
The framework is being established and documented as this dummy project develops.
If you have other use cases, please link:https://github.com/briandominick/liquidoc-poc/issues/new[contribute challenges] in the Issues tab on GitHub!

=== Build

. Clone or download this repository to your local machine.

. Obtain the required Ruby dependency gems.
+
 bundle install

. Run the configured build.
+
 bundle exec liquidoc -c _config/build-portals.yml

LiquiDoc will compile PDFs (see `build/docs/`).
HTML output is limited to standalone files at the moment (see `build/site/`).
Jekyll build functionality is coming soon, as well as possibly other static site generators.

[WARNING]
At this time, the Bundler is configured to use a pre-release version of LiquiDoc hosted on GitHub.
See the bottom line in `Gemfile`.

== Framework

For now, the LiquiDoc CMF is basically a directory structure and a configuration file.

=== Structure

[source]
----
liquidoc-poc/
├── _configs/
│   ├── build-portals.yml
├── _data/
│   ├── asciidoctor.yml
│   ├── company.yml
│   ├── portals.yml
│   ├── products.yml
│   └── terms.yml
├── _templates/
│   ├── asciidoc/
│   │   └── x.adoc
│   └── liquid/
│       ├── product-info.asciidoc
│       └── terms.asciidoc
├── build/*
│   └── [src/]
├── src/
│   ├── includes/
│   ├── portal/
│   ├── topics/
│   └── index.adoc
└── theme/
----

_configs/::
This is where we tell our tooling how to do what.
The YAML file `build-portals.yml` is LiquiDoc instructions for the whole build.
We will add Jekyll config files in here soon.
There could also be Asciidoctor config files here, but attributes should be restricted to build/publish arguments, not documentation content of any kind.

_data/::
+
--
* `asciidoctor.yml` is for Asciidoctor build config _and_ global Asciidoctor settings.
(This should maybe go into `_configs`, since it's build-related.)

* `company.yml` is for information about the company itself.

* `portals.yml` contains 3 blocks, one for each portal.

* `products.yml` contains data about product offerings.

* `terms.yml` is basically the makings of a glossary. It is not ingested as Asciidoctor attributes, but rather pressed into AsciiDoc format by LiquiDoc during preprocessing.
--

_templates/::
This directory is for storing templates used in preprocessing.
The subfolders (such as `liquid`, `asciidoc`, and eventually `haml`) reference the format of the template files they contain.
In the `liquid/` subdirectory, however, contained files, however, are saved with file extensions that represent the type of file they will produce.
So `terms.asciidoc` is formatted in Liquid but generates AsciiDoc-ready output by LiquiDoc.

build/::
This directory is _not_ the repo.
Instead, it is created by LiquiDoc during preprocessing, and it should never be committed (the `.gitignore` file should prevent this).
First, we migrate all of the dirs and files in `src/` into `build/` so we can have everything where we need it for the next steps.
Then we save LiquiDoc-parsed files inside `build/`, specifically for instance in `build/includes/built/`, where our AsciiDoc files know to look at render time.

src/::
This is where _most_ of our content will come from.

includes/:::
Stick all kinds of snippets and partials in here.
If it will never be a standalone topic but will maybe be used in multiple places, such as reused admonitions, place it here.

portal:::
This is for the main content.

topics:::
This is for content that may be a little more general than the portal itself.
For instance, guides or references that might get used as standalone artifacts, belong here.

portal-index.adoc:::
This is the defining file for book builds and the homepage and something of a map for site builds.
It is pretty well self-documented.

theme/::
Files for defining layout and style of the final product go here.
Our goal is to keep the rest of our source code fairly agnostic about what's in here.

=== Process

Asciidoctor is pretty awesome, but it has some serious limitations when it comes to working with data in non-native formats.
Since most other applications don't read AsciiDoc's (fairly sad) data structures, we want AsciiDoc to honor popular open data formats.
Therefore, the power of LiquiDoc is mainly in two of its features:

. AsciiDoc preprocessing.
+
LiquiDoc massages data into AsciiDoc formatted files and saves them in the `build/` directory, where they can be read when we actually render our AsciiDoc files into documents.

. YAML attributes ingest.
+
AsciiDoc uses variables called _attributes_, but it's not very good at consuming these from external files.
LiquiDoc fixes this by letting us convert the data in _multiple_ YAML-formatted flat files into attributes when we go to render our final docs.

With this preprocessing and data-ingest strategy, we greatly expand the single-source (DRY) potential of our docs-as-code system.

== License

This project is released under MIT License.
