- product_slug: basic
  product_name: ACMEdoc Standard
  required_hardware_ram_min-gb: 4
  required_hardware_hdd_min-mb: 120
  versions_supported:
  - 1.0
  - 1.1
  - 1.2
  - 2.0
  - 2.1
- product_slug: premium
  product_name: ACMEdoc Plus
  required_hardware_ram_min-gb: 6
  required_hardware_hdd_min-mb: 200
  versions_supported:
  - 1.2
  - 2.0
  - 2.1
